export const BIBLE_BOOKS = [
  {
    name: "Genesis",
    index: 0,
    chapters: 50,
    firstChapterIndex: 0,
    lastChapterIndex: 49,
    testament: "old",
  },
  {
    name: "Exodus",
    index: 1,
    chapters: 40,
    firstChapterIndex: 0,
    lastChapterIndex: 39,
    testament: "old",
  },
  {
    name: "Leviticus",
    index: 2,
    chapters: 27,
    firstChapterIndex: 0,
    lastChapterIndex: 26,
    testament: "old",
  },
  {
    name: "Numbers",
    index: 3,
    chapters: 36,
    firstChapterIndex: 0,
    lastChapterIndex: 35,
    testament: "old",
  },
  {
    name: "Deuteronomy",
    index: 4,
    chapters: 34,
    firstChapterIndex: 0,
    lastChapterIndex: 33,
    testament: "old",
  },
  {
    name: "Joshua",
    index: 5,
    chapters: 24,
    firstChapterIndex: 0,
    lastChapterIndex: 23,
    testament: "old",
  },
  {
    name: "Judges",
    index: 6,
    chapters: 21,
    firstChapterIndex: 0,
    lastChapterIndex: 20,
    testament: "old",
  },
  {
    name: "Ruth",
    index: 7,
    chapters: 4,
    firstChapterIndex: 0,
    lastChapterIndex: 3,
    testament: "old",
  },
  {
    name: "1 Samuel",
    index: 8,
    chapters: 31,
    firstChapterIndex: 0,
    lastChapterIndex: 30,
    testament: "old",
  },
  {
    name: "2 Samuel",
    index: 9,
    chapters: 24,
    firstChapterIndex: 0,
    lastChapterIndex: 23,
    testament: "old",
  },
  {
    name: "1 Kings",
    index: 10,
    chapters: 22,
    firstChapterIndex: 0,
    lastChapterIndex: 21,
    testament: "old",
  },
  {
    name: "2 Kings",
    index: 11,
    chapters: 25,
    firstChapterIndex: 0,
    lastChapterIndex: 24,
    testament: "old",
  },
  {
    name: "1 Chronicles",
    index: 12,
    chapters: 29,
    firstChapterIndex: 0,
    lastChapterIndex: 28,
    testament: "old",
  },
  {
    name: "2 Chronicles",
    index: 13,
    chapters: 36,
    firstChapterIndex: 0,
    lastChapterIndex: 35,
    testament: "old",
  },
  {
    name: "Ezra",
    index: 14,
    chapters: 10,
    firstChapterIndex: 0,
    lastChapterIndex: 9,
    testament: "old",
  },
  {
    name: "Nehemiah",
    index: 15,
    chapters: 13,
    firstChapterIndex: 0,
    lastChapterIndex: 12,
    testament: "old",
  },
  {
    name: "Esther",
    index: 16,
    chapters: 10,
    firstChapterIndex: 0,
    lastChapterIndex: 9,
    testament: "old",
  },
  {
    name: "Job",
    index: 17,
    chapters: 42,
    firstChapterIndex: 0,
    lastChapterIndex: 41,
    testament: "old",
  },
  {
    name: "Psalms",
    index: 18,
    chapters: 150,
    firstChapterIndex: 0,
    lastChapterIndex: 149,
    testament: "old",
  },
  {
    name: "Proverbs",
    index: 19,
    chapters: 31,
    firstChapterIndex: 0,
    lastChapterIndex: 30,
    testament: "old",
  },
  {
    name: "Ecclesiastes",
    index: 20,
    chapters: 12,
    firstChapterIndex: 0,
    lastChapterIndex: 11,
    testament: "old",
  },
  {
    name: "Song of Solomon",
    index: 21,
    chapters: 8,
    firstChapterIndex: 0,
    lastChapterIndex: 7,
    testament: "old",
  },
  {
    name: "Isaiah",
    index: 22,
    chapters: 66,
    firstChapterIndex: 0,
    lastChapterIndex: 65,
    testament: "old",
  },
  {
    name: "Jeremiah",
    index: 23,
    chapters: 52,
    firstChapterIndex: 0,
    lastChapterIndex: 51,
    testament: "old",
  },
  {
    name: "Lamentations",
    index: 24,
    chapters: 5,
    firstChapterIndex: 0,
    lastChapterIndex: 4,
    testament: "old",
  },
  {
    name: "Ezekiel",
    index: 25,
    chapters: 48,
    firstChapterIndex: 0,
    lastChapterIndex: 47,
    testament: "old",
  },
  {
    name: "Daniel",
    index: 26,
    chapters: 12,
    firstChapterIndex: 0,
    lastChapterIndex: 11,
    testament: "old",
  },
  {
    name: "Hosea",
    index: 27,
    chapters: 14,
    firstChapterIndex: 0,
    lastChapterIndex: 13,
    testament: "old",
  },
  {
    name: "Joel",
    index: 28,
    chapters: 3,
    firstChapterIndex: 0,
    lastChapterIndex: 2,
    testament: "old",
  },
  {
    name: "Amos",
    index: 29,
    chapters: 9,
    firstChapterIndex: 0,
    lastChapterIndex: 8,
    testament: "old",
  },
  {
    name: "Obadiah",
    index: 30,
    chapters: 1,
    firstChapterIndex: 0,
    lastChapterIndex: 0,
    testament: "old",
  },
  {
    name: "Jonah",
    index: 31,
    chapters: 4,
    firstChapterIndex: 0,
    lastChapterIndex: 3,
    testament: "old",
  },
  {
    name: "Micah",
    index: 32,
    chapters: 7,
    firstChapterIndex: 0,
    lastChapterIndex: 6,
    testament: "old",
  },
  {
    name: "Nahum",
    index: 33,
    chapters: 3,
    firstChapterIndex: 0,
    lastChapterIndex: 2,
    testament: "old",
  },
  {
    name: "Habakkuk",
    index: 34,
    chapters: 3,
    firstChapterIndex: 0,
    lastChapterIndex: 2,
    testament: "old",
  },
  {
    name: "Zephaniah",
    index: 35,
    chapters: 3,
    firstChapterIndex: 0,
    lastChapterIndex: 2,
    testament: "old",
  },
  {
    name: "Haggai",
    index: 36,
    chapters: 2,
    firstChapterIndex: 0,
    lastChapterIndex: 1,
    testament: "old",
  },
  {
    name: "Zechariah",
    index: 37,
    chapters: 14,
    firstChapterIndex: 0,
    lastChapterIndex: 13,
    testament: "old",
  },
  {
    name: "Malachi",
    index: 38,
    chapters: 4,
    firstChapterIndex: 0,
    lastChapterIndex: 3,
    testament: "old",
  },
  {
    name: "Matthew",
    index: 39,
    chapters: 28,
    firstChapterIndex: 0,
    lastChapterIndex: 27,
    testament: "new",
  },
  {
    name: "Mark",
    index: 40,
    chapters: 16,
    firstChapterIndex: 0,
    lastChapterIndex: 15,
    testament: "new",
  },
  {
    name: "Luke",
    index: 41,
    chapters: 24,
    firstChapterIndex: 0,
    lastChapterIndex: 23,
    testament: "new",
  },
  {
    name: "John",
    index: 42,
    chapters: 21,
    firstChapterIndex: 0,
    lastChapterIndex: 20,
    testament: "new",
  },
  {
    name: "Acts",
    index: 43,
    chapters: 28,
    firstChapterIndex: 0,
    lastChapterIndex: 27,
    testament: "new",
  },
  {
    name: "Romans",
    index: 44,
    chapters: 16,
    firstChapterIndex: 0,
    lastChapterIndex: 15,
    testament: "new",
  },
  {
    name: "1 Corinthians",
    index: 45,
    chapters: 16,
    firstChapterIndex: 0,
    lastChapterIndex: 15,
    testament: "new",
  },
  {
    name: "2 Corinthians",
    index: 46,
    chapters: 13,
    firstChapterIndex: 0,
    lastChapterIndex: 12,
    testament: "new",
  },
  {
    name: "Galatians",
    index: 47,
    chapters: 6,
    firstChapterIndex: 0,
    lastChapterIndex: 5,
    testament: "new",
  },
  {
    name: "Ephesians",
    index: 48,
    chapters: 6,
    firstChapterIndex: 0,
    lastChapterIndex: 5,
    testament: "new",
  },
  {
    name: "Philippians",
    index: 49,
    chapters: 4,
    firstChapterIndex: 0,
    lastChapterIndex: 3,
    testament: "new",
  },
  {
    name: "Colossians",
    index: 50,
    chapters: 4,
    firstChapterIndex: 0,
    lastChapterIndex: 3,
    testament: "new",
  },
  {
    name: "1 Thessalonians",
    index: 51,
    chapters: 5,
    firstChapterIndex: 0,
    lastChapterIndex: 4,
    testament: "new",
  },
  {
    name: "2 Thessalonians",
    index: 52,
    chapters: 3,
    firstChapterIndex: 0,
    lastChapterIndex: 2,
    testament: "new",
  },
  {
    name: "1 Timothy",
    index: 53,
    chapters: 6,
    firstChapterIndex: 0,
    lastChapterIndex: 5,
    testament: "new",
  },
  {
    name: "2 Timothy",
    index: 54,
    chapters: 4,
    firstChapterIndex: 0,
    lastChapterIndex: 3,
    testament: "new",
  },
  {
    name: "Titus",
    index: 55,
    chapters: 3,
    firstChapterIndex: 0,
    lastChapterIndex: 2,
    testament: "new",
  },
  {
    name: "Philemon",
    index: 56,
    chapters: 1,
    firstChapterIndex: 0,
    lastChapterIndex: 0,
    testament: "new",
  },
  {
    name: "Hebrews",
    index: 57,
    chapters: 13,
    firstChapterIndex: 0,
    lastChapterIndex: 12,
    testament: "new",
  },
  {
    name: "James",
    index: 58,
    chapters: 5,
    firstChapterIndex: 0,
    lastChapterIndex: 4,
    testament: "new",
  },
  {
    name: "1 Peter",
    index: 59,
    chapters: 5,
    firstChapterIndex: 0,
    lastChapterIndex: 4,
    testament: "new",
  },
  {
    name: "2 Peter",
    index: 60,
    chapters: 3,
    firstChapterIndex: 0,
    lastChapterIndex: 2,
    testament: "new",
  },
  {
    name: "1 John",
    index: 61,
    chapters: 5,
    firstChapterIndex: 0,
    lastChapterIndex: 4,
    testament: "new",
  },
  {
    name: "2 John",
    index: 62,
    chapters: 1,
    firstChapterIndex: 0,
    lastChapterIndex: 0,
    testament: "new",
  },
  {
    name: "3 John",
    index: 63,
    chapters: 1,
    firstChapterIndex: 0,
    lastChapterIndex: 0,
    testament: "new",
  },
  {
    name: "Jude",
    index: 64,
    chapters: 1,
    firstChapterIndex: 0,
    lastChapterIndex: 0,
    testament: "new",
  },
  {
    name: "Revelation",
    index: 65,
    chapters: 22,
    firstChapterIndex: 0,
    lastChapterIndex: 21,
    testament: "new",
  },
];
