export const BIBLE_BOOKS = [
  {
    name: "Genesis",
    shortName: "Gen",
    index: 0,
    chapters: 50,
    firstChapterIndex: 0,
    lastChapterIndex: 49,
    testament: "old",
  },
  {
    name: "Exodus",
    shortName: "Exod",
    index: 1,
    chapters: 40,
    firstChapterIndex: 0,
    lastChapterIndex: 39,
    testament: "old",
  },
  {
    name: "Leviticus",
    shortName: "Lev",
    index: 2,
    chapters: 27,
    firstChapterIndex: 0,
    lastChapterIndex: 26,
    testament: "old",
  },
  {
    name: "Numbers",
    shortName: "Num",
    index: 3,
    chapters: 36,
    firstChapterIndex: 0,
    lastChapterIndex: 35,
    testament: "old",
  },
  {
    name: "Deuteronomy",
    shortName: "Deut",
    index: 4,
    chapters: 34,
    firstChapterIndex: 0,
    lastChapterIndex: 33,
    testament: "old",
  },
  {
    name: "Joshua",
    shortName: "Josh",
    index: 5,
    chapters: 24,
    firstChapterIndex: 0,
    lastChapterIndex: 23,
    testament: "old",
  },
  {
    name: "Judges",
    shortName: "Judg",
    index: 6,
    chapters: 21,
    firstChapterIndex: 0,
    lastChapterIndex: 20,
    testament: "old",
  },
  {
    name: "Ruth",
    shortName: "Ruth",
    index: 7,
    chapters: 4,
    firstChapterIndex: 0,
    lastChapterIndex: 3,
    testament: "old",
  },
  {
    name: "1 Samuel",
    shortName: "1Sam",
    index: 8,
    chapters: 31,
    firstChapterIndex: 0,
    lastChapterIndex: 30,
    testament: "old",
  },
  {
    name: "2 Samuel",
    shortName: "2Sam",
    index: 9,
    chapters: 24,
    firstChapterIndex: 0,
    lastChapterIndex: 23,
    testament: "old",
  },
  {
    name: "1 Kings",
    shortName: "1Kgs",
    index: 10,
    chapters: 22,
    firstChapterIndex: 0,
    lastChapterIndex: 21,
    testament: "old",
  },
  {
    name: "2 Kings",
    shortName: "2Kgs",
    index: 11,
    chapters: 25,
    firstChapterIndex: 0,
    lastChapterIndex: 24,
    testament: "old",
  },
  {
    name: "1 Chronicles",
    shortName: "1Chr",
    index: 12,
    chapters: 29,
    firstChapterIndex: 0,
    lastChapterIndex: 28,
    testament: "old",
  },
  {
    name: "2 Chronicles",
    shortName: "2Chr",
    index: 13,
    chapters: 36,
    firstChapterIndex: 0,
    lastChapterIndex: 35,
    testament: "old",
  },
  {
    name: "Ezra",
    shortName: "Ezra",
    index: 14,
    chapters: 10,
    firstChapterIndex: 0,
    lastChapterIndex: 9,
    testament: "old",
  },
  {
    name: "Nehemiah",
    shortName: "Neh",
    index: 15,
    chapters: 13,
    firstChapterIndex: 0,
    lastChapterIndex: 12,
    testament: "old",
  },
  {
    name: "Esther",
    shortName: "Esth",
    index: 16,
    chapters: 10,
    firstChapterIndex: 0,
    lastChapterIndex: 9,
    testament: "old",
  },
  {
    name: "Job",
    shortName: "Job",
    index: 17,
    chapters: 42,
    firstChapterIndex: 0,
    lastChapterIndex: 41,
    testament: "old",
  },
  {
    name: "Psalms",
    shortName: "Ps",
    index: 18,
    chapters: 150,
    firstChapterIndex: 0,
    lastChapterIndex: 149,
    testament: "old",
  },
  {
    name: "Proverbs",
    shortName: "Prov",
    index: 19,
    chapters: 31,
    firstChapterIndex: 0,
    lastChapterIndex: 30,
    testament: "old",
  },
  {
    name: "Ecclesiastes",
    shortName: "Eccl",
    index: 20,
    chapters: 12,
    firstChapterIndex: 0,
    lastChapterIndex: 11,
    testament: "old",
  },
  {
    name: "Song of Solomon",
    shortName: "Song",
    index: 21,
    chapters: 8,
    firstChapterIndex: 0,
    lastChapterIndex: 7,
    testament: "old",
  },
  {
    name: "Isaiah",
    shortName: "Isa",
    index: 22,
    chapters: 66,
    firstChapterIndex: 0,
    lastChapterIndex: 65,
    testament: "old",
  },
  {
    name: "Jeremiah",
    shortName: "Jer",
    index: 23,
    chapters: 52,
    firstChapterIndex: 0,
    lastChapterIndex: 51,
    testament: "old",
  },
  {
    name: "Lamentations",
    shortName: "Lam",
    index: 24,
    chapters: 5,
    firstChapterIndex: 0,
    lastChapterIndex: 4,
    testament: "old",
  },
  {
    name: "Ezekiel",
    shortName: "Ezek",
    index: 25,
    chapters: 48,
    firstChapterIndex: 0,
    lastChapterIndex: 47,
    testament: "old",
  },
  {
    name: "Daniel",
    shortName: "Dan",
    index: 26,
    chapters: 12,
    firstChapterIndex: 0,
    lastChapterIndex: 11,
    testament: "old",
  },
  {
    name: "Hosea",
    shortName: "Hos",
    index: 27,
    chapters: 14,
    firstChapterIndex: 0,
    lastChapterIndex: 13,
    testament: "old",
  },
  {
    name: "Joel",
    shortName: "Joel",
    index: 28,
    chapters: 3,
    firstChapterIndex: 0,
    lastChapterIndex: 2,
    testament: "old",
  },
  {
    name: "Amos",
    shortName: "Amos",
    index: 29,
    chapters: 9,
    firstChapterIndex: 0,
    lastChapterIndex: 8,
    testament: "old",
  },
  {
    name: "Obadiah",
    shortName: "Obad",
    index: 30,
    chapters: 1,
    firstChapterIndex: 0,
    lastChapterIndex: 0,
    testament: "old",
  },
  {
    name: "Jonah",
    shortName: "Jonah",
    index: 31,
    chapters: 4,
    firstChapterIndex: 0,
    lastChapterIndex: 3,
    testament: "old",
  },
  {
    name: "Micah",
    shortName: "Mic",
    index: 32,
    chapters: 7,
    firstChapterIndex: 0,
    lastChapterIndex: 6,
    testament: "old",
  },
  {
    name: "Nahum",
    shortName: "Nah",
    index: 33,
    chapters: 3,
    firstChapterIndex: 0,
    lastChapterIndex: 2,
    testament: "old",
  },
  {
    name: "Habakkuk",
    shortName: "Hab",
    index: 34,
    chapters: 3,
    firstChapterIndex: 0,
    lastChapterIndex: 2,
    testament: "old",
  },
  {
    name: "Zephaniah",
    shortName: "Zeph",
    index: 35,
    chapters: 3,
    firstChapterIndex: 0,
    lastChapterIndex: 2,
    testament: "old",
  },
  {
    name: "Haggai",
    shortName: "Hag",
    index: 36,
    chapters: 2,
    firstChapterIndex: 0,
    lastChapterIndex: 1,
    testament: "old",
  },
  {
    name: "Zechariah",
    shortName: "Zech",
    index: 37,
    chapters: 14,
    firstChapterIndex: 0,
    lastChapterIndex: 13,
    testament: "old",
  },
  {
    name: "Malachi",
    shortName: "Mal",
    index: 38,
    chapters: 4,
    firstChapterIndex: 0,
    lastChapterIndex: 3,
    testament: "old",
  },
  {
    name: "Matthew",
    shortName: "Matt",
    index: 39,
    chapters: 28,
    firstChapterIndex: 0,
    lastChapterIndex: 27,
    testament: "new",
  },
  {
    name: "Mark",
    shortName: "Mark",
    index: 40,
    chapters: 16,
    firstChapterIndex: 0,
    lastChapterIndex: 15,
    testament: "new",
  },
  {
    name: "Luke",
    shortName: "Luke",
    index: 41,
    chapters: 24,
    firstChapterIndex: 0,
    lastChapterIndex: 23,
    testament: "new",
  },
  {
    name: "John",
    shortName: "John",
    index: 42,
    chapters: 21,
    firstChapterIndex: 0,
    lastChapterIndex: 20,
    testament: "new",
  },
  {
    name: "Acts",
    shortName: "Acts",
    index: 43,
    chapters: 28,
    firstChapterIndex: 0,
    lastChapterIndex: 27,
    testament: "new",
  },
  {
    name: "Romans",
    shortName: "Rom",
    index: 44,
    chapters: 16,
    firstChapterIndex: 0,
    lastChapterIndex: 15,
    testament: "new",
  },
  {
    name: "1 Corinthians",
    shortName: "1Cor",
    index: 45,
    chapters: 16,
    firstChapterIndex: 0,
    lastChapterIndex: 15,
    testament: "new",
  },
  {
    name: "2 Corinthians",
    shortName: "2Cor",
    index: 46,
    chapters: 13,
    firstChapterIndex: 0,
    lastChapterIndex: 12,
    testament: "new",
  },
  {
    name: "Galatians",
    shortName: "Gal",
    index: 47,
    chapters: 6,
    firstChapterIndex: 0,
    lastChapterIndex: 5,
    testament: "new",
  },
  {
    name: "Ephesians",
    shortName: "Eph",
    index: 48,
    chapters: 6,
    firstChapterIndex: 0,
    lastChapterIndex: 5,
    testament: "new",
  },
  {
    name: "Philippians",
    shortName: "Phil",
    index: 49,
    chapters: 4,
    firstChapterIndex: 0,
    lastChapterIndex: 3,
    testament: "new",
  },
  {
    name: "Colossians",
    shortName: "Col",
    index: 50,
    chapters: 4,
    firstChapterIndex: 0,
    lastChapterIndex: 3,
    testament: "new",
  },
  {
    name: "1 Thessalonians",
    shortName: "1Thess",
    index: 51,
    chapters: 5,
    firstChapterIndex: 0,
    lastChapterIndex: 4,
    testament: "new",
  },
  {
    name: "2 Thessalonians",
    shortName: "2Thess",
    index: 52,
    chapters: 3,
    firstChapterIndex: 0,
    lastChapterIndex: 2,
    testament: "new",
  },
  {
    name: "1 Timothy",
    shortName: "1Tim",
    index: 53,
    chapters: 6,
    firstChapterIndex: 0,
    lastChapterIndex: 5,
    testament: "new",
  },
  {
    name: "2 Timothy",
    shortName: "2Tim",
    index: 54,
    chapters: 4,
    firstChapterIndex: 0,
    lastChapterIndex: 3,
    testament: "new",
  },
  {
    name: "Titus",
    shortName: "Titus",
    index: 55,
    chapters: 3,
    firstChapterIndex: 0,
    lastChapterIndex: 2,
    testament: "new",
  },
  {
    name: "Philemon",
    shortName: "Phlm",
    index: 56,
    chapters: 1,
    firstChapterIndex: 0,
    lastChapterIndex: 0,
    testament: "new",
  },
  {
    name: "Hebrews",
    shortName: "Heb",
    index: 57,
    chapters: 13,
    firstChapterIndex: 0,
    lastChapterIndex: 12,
    testament: "new",
  },
  {
    name: "James",
    shortName: "Jas",
    index: 58,
    chapters: 5,
    firstChapterIndex: 0,
    lastChapterIndex: 4,
    testament: "new",
  },
  {
    name: "1 Peter",
    shortName: "1Pet",
    index: 59,
    chapters: 5,
    firstChapterIndex: 0,
    lastChapterIndex: 4,
    testament: "new",
  },
  {
    name: "2 Peter",
    shortName: "2Pet",
    index: 60,
    chapters: 3,
    firstChapterIndex: 0,
    lastChapterIndex: 2,
    testament: "new",
  },
  {
    name: "1 John",
    shortName: "1John",
    index: 61,
    chapters: 5,
    firstChapterIndex: 0,
    lastChapterIndex: 4,
    testament: "new",
  },
  {
    name: "2 John",
    shortName: "2John",
    index: 62,
    chapters: 1,
    firstChapterIndex: 0,
    lastChapterIndex: 0,
    testament: "new",
  },
  {
    name: "3 John",
    shortName: "3John",
    index: 63,
    chapters: 1,
    firstChapterIndex: 0,
    lastChapterIndex: 0,
    testament: "new",
  },
  {
    name: "Jude",
    shortName: "Jude",
    index: 64,
    chapters: 1,
    firstChapterIndex: 0,
    lastChapterIndex: 0,
    testament: "new",
  },
  {
    name: "Revelation",
    shortName: "Rev",
    index: 65,
    chapters: 22,
    firstChapterIndex: 0,
    lastChapterIndex: 21,
    testament: "new",
  },
];
